'use strict';
// Food database: [name, serving, calories, color]
// Color follows calorie density: G = green (< 1 cal/gram), Y = yellow (1–2.4), R = red (> 2.4).
// Calories are typical values for the listed serving.
const FOOD_ROWS = [
  // Fruit
  ['Apple', '1 medium', 95, 'G'], ['Banana', '1 medium', 105, 'G'], ['Orange', '1 medium', 62, 'G'],
  ['Grapes', '1 cup', 104, 'G'], ['Strawberries', '1 cup', 50, 'G'], ['Blueberries', '1 cup', 85, 'G'],
  ['Watermelon', '1 cup', 46, 'G'], ['Cantaloupe', '1 cup', 54, 'G'], ['Pear', '1 medium', 100, 'G'],
  ['Peach', '1 medium', 60, 'G'], ['Pineapple', '1 cup', 82, 'G'], ['Clementine', '1', 35, 'G'],
  ['Applesauce, unsweetened', '1/2 cup', 50, 'G'], ['Avocado', '1/2', 120, 'Y'],
  ['Raisins', '1/4 cup', 108, 'R'], ['Dried cranberries', '1/4 cup', 123, 'R'],
  // Vegetables
  ['Salad greens', '2 cups', 15, 'G'], ['Broccoli', '1 cup', 55, 'G'], ['Carrots', '1 cup', 50, 'G'],
  ['Baby carrots', '10', 35, 'G'], ['Green beans', '1 cup', 44, 'G'], ['Tomato', '1 medium', 22, 'G'],
  ['Cucumber', '1 cup', 16, 'G'], ['Corn', '1 cup', 130, 'G'], ['Corn on the cob', '1 ear', 90, 'G'],
  ['Baked potato, plain', '1 medium', 160, 'G'], ['Sweet potato', '1 medium', 115, 'G'],
  ['Spinach, cooked', '1 cup', 41, 'G'], ['Mixed vegetables', '1 cup', 80, 'G'], ['Onion', '1/2 cup', 32, 'G'],
  ['Bell pepper', '1 medium', 30, 'G'], ['Mushrooms', '1 cup', 15, 'G'], ['Cauliflower', '1 cup', 27, 'G'],
  ['Zucchini', '1 cup', 20, 'G'], ['Asparagus', '6 spears', 20, 'G'], ['Celery', '2 stalks', 12, 'G'],
  ['Side salad, no dressing', '1 bowl', 35, 'G'], ['Coleslaw', '1/2 cup', 150, 'Y'],
  // Grains & bread
  ['Oatmeal, cooked', '1 cup', 165, 'G'], ['Whole wheat bread', '1 slice', 80, 'Y'], ['White bread', '1 slice', 75, 'Y'],
  ['English muffin', '1', 135, 'Y'], ['Bagel, plain', '1', 280, 'R'], ['Brown rice', '1 cup', 215, 'Y'],
  ['White rice', '1 cup', 205, 'Y'], ['Pasta, cooked', '1 cup', 220, 'Y'], ['Whole wheat pasta', '1 cup', 175, 'Y'],
  ['Cold cereal', '1 cup', 110, 'R'], ['Granola', '1/2 cup', 300, 'R'], ['Flour tortilla', '1 (8 inch)', 145, 'R'],
  ['Corn tortilla', '1', 55, 'Y'], ['Crackers', '5', 70, 'R'], ['Pancakes', '2 medium', 350, 'Y'],
  ['Waffle, frozen', '1', 95, 'R'], ['Dinner roll', '1', 110, 'R'], ['Hamburger bun', '1', 120, 'R'],
  ['Biscuit', '1', 190, 'R'], ['Cornbread', '1 piece', 200, 'R'],
  // Protein
  ['Chicken breast, grilled', '4 oz', 185, 'Y'], ['Rotisserie chicken', '4 oz', 230, 'Y'],
  ['Turkey, deli sliced', '3 oz', 90, 'Y'], ['Salmon, baked', '4 oz', 235, 'Y'], ['Tuna in water', '1 can', 120, 'Y'],
  ['Shrimp', '4 oz', 120, 'Y'], ['White fish, baked', '4 oz', 145, 'Y'], ['Egg', '1 large', 72, 'Y'],
  ['Egg whites', '1/2 cup', 63, 'G'], ['Scrambled eggs', '2 eggs', 180, 'Y'], ['Hard-boiled egg', '1', 78, 'Y'],
  ['Lean ground beef (90%)', '4 oz cooked', 245, 'Y'], ['Hamburger patty (80%)', '4 oz cooked', 290, 'R'],
  ['Steak, sirloin', '6 oz', 320, 'Y'], ['Pork chop', '5 oz', 250, 'Y'], ['Pork tenderloin', '4 oz', 160, 'Y'],
  ['Bacon', '2 slices', 90, 'R'], ['Turkey bacon', '2 slices', 70, 'Y'], ['Sausage links', '2', 170, 'R'],
  ['Ham', '3 oz', 100, 'Y'], ['Tofu', '1/2 cup', 90, 'G'], ['Black beans', '1/2 cup', 115, 'Y'],
  ['Lentils', '1/2 cup', 115, 'Y'], ['Chickpeas', '1/2 cup', 135, 'Y'], ['Hot dog with bun', '1', 280, 'R'],
  ['Meatloaf', '1 slice', 250, 'Y'], ['Pot roast', '4 oz', 250, 'Y'],
  // Dairy
  ['Skim milk', '1 cup', 85, 'G'], ['2% milk', '1 cup', 122, 'Y'], ['Whole milk', '1 cup', 150, 'Y'],
  ['Almond milk, unsweetened', '1 cup', 35, 'G'], ['Greek yogurt, plain nonfat', '3/4 cup', 100, 'G'],
  ['Flavored yogurt', '1 cup', 150, 'Y'], ['Cottage cheese, low-fat', '1/2 cup', 90, 'G'],
  ['Cheddar cheese', '1 oz', 115, 'R'], ['String cheese', '1 stick', 80, 'R'], ['American cheese', '1 slice', 60, 'R'],
  ['Parmesan, grated', '2 tbsp', 40, 'R'], ['Butter', '1 tbsp', 100, 'R'], ['Ice cream', '1/2 cup', 140, 'R'],
  ['Frozen yogurt', '1/2 cup', 110, 'Y'],
  // Fats, nuts, dressings
  ['Peanut butter', '2 tbsp', 190, 'R'], ['Almonds', '1 oz (23)', 164, 'R'], ['Mixed nuts', '1 oz', 170, 'R'],
  ['Walnuts', '1 oz', 185, 'R'], ['Olive oil', '1 tbsp', 120, 'R'], ['Mayonnaise', '1 tbsp', 95, 'R'],
  ['Light mayo', '1 tbsp', 35, 'Y'], ['Ranch dressing', '2 tbsp', 130, 'R'], ['Light Italian dressing', '2 tbsp', 30, 'Y'],
  ['Hummus', '2 tbsp', 70, 'Y'], ['Cream cheese', '1 tbsp', 50, 'R'], ['Sour cream', '2 tbsp', 60, 'Y'],
  // Meals & restaurant
  ['Cheeseburger (fast food, small)', '1', 300, 'R'], ['Large burger', '1', 550, 'R'], ['French fries', 'medium', 365, 'R'],
  ['Cheese pizza', '1 slice', 285, 'R'], ['Pepperoni pizza', '1 slice', 310, 'R'], ['Turkey sandwich', '1', 350, 'Y'],
  ['Ham & cheese sandwich', '1', 380, 'Y'], ['BLT sandwich', '1', 400, 'R'], ['Grilled cheese', '1', 390, 'R'],
  ['Tuna salad sandwich', '1', 450, 'R'], ['Sub sandwich, turkey', '6 inch', 280, 'Y'],
  ['Chicken noodle soup', '1 cup', 60, 'G'], ['Vegetable soup', '1 cup', 80, 'G'], ['Chili', '1 cup', 260, 'Y'],
  ['Spaghetti with meat sauce', '1.5 cups', 450, 'Y'], ['Taco', '1', 170, 'Y'], ['Burrito', '1', 600, 'Y'],
  ['Chicken Caesar salad', '1 bowl', 450, 'Y'], ['Grilled chicken salad, light dressing', '1 bowl', 300, 'Y'],
  ['Fried chicken', '1 piece', 320, 'R'], ['Chicken tenders', '3 pieces', 400, 'R'],
  ['Veggie omelet with cheese', '2 eggs', 300, 'Y'], ['Mac and cheese', '1 cup', 350, 'Y'],
  ['Chicken stir-fry', '1.5 cups', 350, 'Y'], ['Sushi roll', '8 pieces', 300, 'Y'], ['Mashed potatoes', '1 cup', 240, 'Y'],
  ['Baked beans', '1/2 cup', 120, 'Y'], ['Lasagna', '1 piece', 400, 'Y'], ['Fish and chips', '1 plate', 850, 'R'],
  ['Breakfast sandwich (egg, cheese, meat)', '1', 450, 'R'],
  // Snacks & sweets
  ['Potato chips', '1 oz', 150, 'R'], ['Pretzels', '1 oz', 110, 'R'], ['Popcorn, light', '3 cups', 100, 'Y'],
  ['Tortilla chips', '1 oz', 140, 'R'], ['Cookie', '1 medium', 150, 'R'], ['Chocolate bar', '1', 230, 'R'],
  ['Dark chocolate', '1 oz', 170, 'R'], ['Donut', '1', 250, 'R'], ['Muffin', '1', 400, 'R'], ['Cake', '1 slice', 350, 'R'],
  ['Pie', '1 slice', 400, 'R'], ['Granola bar', '1', 120, 'R'], ['Protein bar', '1', 200, 'R'],
  ['Pudding cup', '1', 110, 'Y'], ['Sugar-free gelatin', '1 cup', 10, 'G'], ['Rice cake', '1', 35, 'R'],
  // Drinks
  ['Coffee, black', '1 cup', 5, 'G'], ['Coffee with cream & sugar', '1 cup', 70, 'Y'], ['Latte', '12 oz', 190, 'Y'],
  ['Tea, unsweetened', '1 cup', 0, 'G'], ['Sweet tea', '16 oz', 180, 'R'], ['Soda', '12 oz can', 150, 'R'],
  ['Diet soda', '12 oz can', 0, 'G'], ['Orange juice', '1 cup', 110, 'Y'], ['Beer', '12 oz', 150, 'Y'],
  ['Light beer', '12 oz', 100, 'Y'], ['Wine', '5 oz glass', 125, 'R'], ['Liquor', '1.5 oz shot', 100, 'R'],
  ['Sports drink', '20 oz', 140, 'Y'], ['Smoothie', '16 oz', 300, 'Y'], ['Protein shake', '1 bottle', 160, 'Y'],
  // Condiments
  ['Ketchup', '1 tbsp', 20, 'Y'], ['Mustard', '1 tsp', 5, 'G'], ['Salsa', '2 tbsp', 10, 'G'], ['Sugar', '1 tsp', 16, 'R'],
  ['Honey', '1 tbsp', 64, 'R'], ['Maple syrup', '2 tbsp', 110, 'R'], ['Jam', '1 tbsp', 50, 'R'],
  ['Gravy', '1/4 cup', 30, 'Y'], ['BBQ sauce', '2 tbsp', 60, 'R'],
];
const FOODS = FOOD_ROWS.map(([name, serving, cal, color], i) => ({ id: 'f' + i, name, serving, cal, color }));

// Daily lessons: short, practical, one idea each.
const LESSONS = [
  { title: 'Welcome: small steps win', body: [
    'This app is built around one idea: small, steady changes beat big, short-lived ones.',
    'You don\'t need to be perfect. You need to be consistent. Logging most of what you eat, most days, is enough to make real progress.',
    'Each day you\'ll get one short lesson like this. Read it with your morning coffee, and try the idea that day.'],
    quiz: { q: 'What matters most for long-term weight loss?', options: ['Being perfect every day', 'Being consistent most days', 'Eating as little as possible'], answer: 1,
      why: 'Consistency adds up. Perfection tends to lead to burnout.' } },
  { title: 'The color system', body: [
    'Every food here gets a color based on how many calories it packs into each bite.',
    'Green foods (vegetables, fruit, soups, skim milk) are filling for few calories. Yellow foods (lean meats, grains, eggs) are the middle ground. Red foods (nuts, cheese, sweets, fried food) pack a lot of calories into a small amount.',
    'No food is forbidden. Red just means "watch the portion." A good day is roughly 30% green, 45% yellow and 25% red, measured in calories.'],
    quiz: { q: 'Red foods are…', options: ['Banned', 'Fine in smaller portions', 'Always unhealthy'], answer: 1,
      why: 'Red foods like nuts and olive oil can be healthy. They are just calorie-dense, so portions matter.' } },
  { title: 'Why logging works', body: [
    'People who write down what they eat lose about twice as much weight as people who don\'t.',
    'Logging isn\'t about judgment. It makes the invisible visible: the handful of chips, the second roll, the creamer in the coffee.',
    'Tip: log right after you eat, or even before. It takes 20 seconds and stops you guessing at the end of the day.'],
    quiz: { q: 'When is the best time to log a meal?', options: ['At the end of the week', 'Right when you eat it', 'Only when you overeat'], answer: 1,
      why: 'Logging as you go is faster and more accurate than trying to remember later.' } },
  { title: 'Fill half your plate with green', body: [
    'Here\'s an easy trick that doesn\'t need counting: make half your plate vegetables, a quarter protein and a quarter starch.',
    'Vegetables take up room in your stomach and signal fullness, for very few calories.',
    'Try it at dinner tonight. Frozen vegetables count, and they\'re just as nutritious as fresh.'],
    quiz: { q: 'How much of your plate should be vegetables?', options: ['A quarter', 'Half', 'None, if you\'re eating protein'], answer: 1,
      why: 'Half a plate of vegetables fills you up and cuts calories without leaving you hungry.' } },
  { title: 'Protein keeps you full', body: [
    'Protein is the most filling nutrient. It also helps you keep your muscle while you lose fat, which matters more as we get older.',
    'Aim to have some protein at every meal: eggs, Greek yogurt, chicken, fish, beans, cottage cheese or lean meat.',
    'A breakfast with protein often means fewer cravings by mid-morning.'],
    quiz: { q: 'Why is protein especially important while losing weight?', options: ['It has no calories', 'It keeps you full and protects muscle', 'It speeds up digestion'], answer: 1,
      why: 'Protein keeps you satisfied and helps you keep muscle while you lose fat.' } },
  { title: 'The hunger scale', body: [
    'Rate your hunger from 1 (starving) to 10 (stuffed Thanksgiving-full).',
    'Try to start eating around 3 or 4 (hungry, not starving) and stop around 6 or 7 (satisfied, not full).',
    'Before you eat today, ask yourself: "What number am I?" Sometimes the answer is "I\'m not hungry, I\'m bored."'],
    quiz: { q: 'When should you aim to stop eating?', options: ['When the plate is empty', 'When you feel satisfied, around 6–7', 'When you feel stuffed'], answer: 1,
      why: 'Stopping at "satisfied" leaves room for your body to catch up. Fullness signals lag by about 20 minutes.' } },
  { title: 'Slow down', body: [
    'It takes about 20 minutes for your stomach to tell your brain it\'s full.',
    'If you finish a meal in 7 minutes, you can easily overshoot before the signal arrives.',
    'Try this: put your fork down between bites, and take a sip of water halfway through the meal.'],
    quiz: { q: 'About how long does it take to feel full?', options: ['2 minutes', '20 minutes', '2 hours'], answer: 1,
      why: 'Eating slowly gives your fullness signals time to catch up.' } },
  { title: 'Water first', body: [
    'Thirst is easy to mistake for hunger.',
    'Drinking a glass of water before each meal helps many people eat less without trying.',
    'Use the water tracker on the Today screen. Aim for about 8 glasses, more if it\'s hot or you\'re active.'],
    quiz: { q: 'A glass of water before meals can…', options: ['Help you eat less', 'Burn fat directly', 'Replace a meal'], answer: 0,
      why: 'Water adds volume and can blunt hunger. It isn\'t magic, but it helps.' } },
  { title: 'Liquid calories', body: [
    'Soda, sweet tea, juice, fancy coffee drinks and alcohol add calories without making you feel full.',
    'One regular soda a day is about 150 calories. Over a year that works out to around 15 pounds.',
    'Swap one sweet drink a day for water, sparkling water, unsweetened tea or diet soda.'],
    quiz: { q: 'Why are liquid calories tricky?', options: ['They don\'t fill you up', 'They have no calories', 'They are always healthy'], answer: 0,
      why: 'Your body doesn\'t register drinks as "food," so you don\'t eat less later to make up for them.' } },
  { title: 'Portions: use your hand', body: [
    'No scale? Use your hand. Your palm is a serving of meat (about 4 oz). Your fist is a cup of rice or pasta. Your thumb is a tablespoon of peanut butter or oil.',
    'Restaurant portions are often two or three servings.',
    'Try this: when a big plate arrives, set half aside or box it up before you start eating.'],
    quiz: { q: 'A serving of meat is about the size of your…', options: ['Thumb', 'Palm', 'Whole hand spread out'], answer: 1,
      why: 'A palm-sized piece of meat is about 3–4 oz.' } },
  { title: 'Plan for snacks', body: [
    'Snacking isn\'t bad. Unplanned snacking is what adds up.',
    'Keep green and yellow snacks easy to reach: cut fruit, baby carrots, Greek yogurt, a hard-boiled egg or string cheese.',
    'Put red snacks out of sight: in a cupboard, on a high shelf, or not in the house at all.'],
    quiz: { q: 'What\'s a smart snack strategy?', options: ['Never snack', 'Keep healthy snacks visible and treats out of sight', 'Snack only at night'], answer: 1,
      why: 'What we see is what we eat. Make the easy choice the good choice.' } },
  { title: 'Walking counts', body: [
    'You don\'t need a gym. Walking is one of the best things you can do for weight, heart health, blood sugar and mood.',
    'A 10-minute walk after meals is especially good for your blood sugar.',
    'Log your steps each day. If you\'re under 5,000, try to add 1,000 more this week.'],
    quiz: { q: 'A short walk after meals helps with…', options: ['Blood sugar', 'Nothing', 'Only weight'], answer: 0,
      why: 'Muscles use sugar from your blood when they move, so a walk after eating smooths out spikes.' } },
  { title: 'Keep your muscle', body: [
    'After about age 50, we lose muscle each year unless we use it. Muscle keeps you strong and steady, and it burns calories even at rest.',
    'Simple strength moves count: standing up from a chair 10 times, wall push-ups, carrying groceries, light dumbbells.',
    'Two or three short sessions a week make a real difference. Check with your doctor if you\'re starting something new.'],
    quiz: { q: 'Why does strength training matter more with age?', options: ['It doesn\'t', 'We naturally lose muscle unless we use it', 'It only helps athletes'], answer: 1,
      why: 'Using your muscles keeps them. That protects balance, strength and metabolism.' } },
  { title: 'Sleep and hunger', body: [
    'Poor sleep raises the hormone that makes you hungry and lowers the one that makes you feel full.',
    'People who sleep under 6 hours tend to eat more the next day, especially sweets and snacks.',
    'Aim for 7–8 hours. Try a steady bedtime and no screens for the last half hour.'],
    quiz: { q: 'Short sleep tends to…', options: ['Increase hunger', 'Decrease hunger', 'Have no effect'], answer: 0,
      why: 'Sleep loss upsets your hunger hormones and makes cravings stronger.' } },
  { title: 'Emotional eating', body: [
    'We don\'t only eat because we\'re hungry. We eat when we\'re stressed, bored, lonely, tired or celebrating.',
    'That\'s normal. The goal is to notice it. Before a snack, ask: "Am I hungry, or am I feeling something?"',
    'If it\'s a feeling, try something else first for 10 minutes: a walk, a phone call, a glass of water.'],
    quiz: { q: 'What\'s the first step with emotional eating?', options: ['Feeling guilty', 'Noticing it', 'Ignoring it'], answer: 1,
      why: 'Noticing gives you a moment to choose, instead of eating on autopilot.' } },
  { title: 'Triggers and routines', body: [
    'Habits run on a loop: a trigger (the TV turns on), a routine (the chips come out), then a reward (it tastes good and feels relaxing).',
    'You don\'t have to fight the trigger. Swap the routine: TV on, then tea or a bowl of popcorn instead of chips.',
    'Pick one habit loop you\'d like to change this week.'],
    quiz: { q: 'The easiest way to change a habit is to…', options: ['Swap the routine', 'Use willpower forever', 'Avoid all triggers'], answer: 0,
      why: 'Keeping the trigger and reward but changing the routine is much easier than white-knuckling it.' } },
  { title: 'Slip-ups are normal', body: [
    'You will have days where you go over. Everyone does.',
    'The danger isn\'t one big meal. It\'s the "I already blew it, so forget it" thinking that follows.',
    'After a slip, get right back on track at the next meal, not next Monday.'],
    quiz: { q: 'After an off day, you should…', options: ['Skip meals to make up for it', 'Get back on track at the next meal', 'Start over next month'], answer: 1,
      why: 'One meal doesn\'t undo your progress. Quitting does.' } },
  { title: 'Weigh-ins: the right way', body: [
    'Weight goes up and down day to day with water, salt and digestion. A 2–3 lb swing is normal.',
    'Weigh in at the same time: morning, after the bathroom, before eating.',
    'Look at the trend over weeks, not any single day. The Progress tab shows the line.'],
    quiz: { q: 'Your weight went up 2 lb overnight. Most likely…', options: ['You gained 2 lb of fat', 'It\'s normal water fluctuation', 'The plan isn\'t working'], answer: 1,
      why: 'Gaining 2 lb of fat takes about 7,000 extra calories. Overnight jumps are water.' } },
  { title: 'Eating out', body: [
    'Restaurants are designed to make food taste great, usually with lots of butter, oil and salt, in big portions.',
    'Tricks: look at the menu ahead of time, ask for dressing on the side, swap fries for a vegetable, and box half before you start.',
    'Grilled, baked or steamed usually beats fried, crispy or creamy.'],
    quiz: { q: 'Which is usually the lighter choice?', options: ['Crispy chicken', 'Grilled chicken', 'They\'re the same'], answer: 1,
      why: '"Crispy" usually means fried, which can add hundreds of calories.' } },
  { title: 'Weekends', body: [
    'Many people are on track Monday to Friday, then undo half the week on the weekend.',
    'You don\'t have to be strict on weekends. Just keep logging, and plan for the big meal.',
    'If you know Saturday dinner will be big, go lighter and greener at breakfast and lunch.'],
    quiz: { q: 'A good weekend strategy is to…', options: ['Stop logging', 'Plan around the big meal', 'Skip all meals'], answer: 1,
      why: 'Planning ahead lets you enjoy the meal without going far over.' } },
  { title: 'Reading a food label', body: [
    'Check the serving size first. Everything else on the label is based on it, and a bag of chips might be 3 servings.',
    'Then look at calories, protein and fiber. More protein and fiber usually means more filling.',
    'Watch sodium if blood pressure is a concern. Under about 600 mg per meal is a good guideline.'],
    quiz: { q: 'What should you check first on a label?', options: ['Serving size', 'Sugar', 'The picture'], answer: 0,
      why: 'All the numbers depend on serving size. Double the serving, double everything.' } },
  { title: 'Fiber is your friend', body: [
    'Fiber slows digestion, steadies blood sugar and keeps you full.',
    'You\'ll find it in vegetables, fruit, beans, lentils, oats and whole grains.',
    'Easy swaps: oatmeal instead of cold cereal, whole-wheat bread instead of white, and add beans to soups and salads.'],
    quiz: { q: 'Which is highest in fiber?', options: ['White bread', 'Black beans', 'Cheese'], answer: 1,
      why: 'Beans are among the best sources of fiber, and they also have protein.' } },
  { title: 'Cooking at home', body: [
    'Home cooking gives you control over oil, butter, salt and portions.',
    'It doesn\'t have to be fancy: a sheet pan with chicken and vegetables, olive oil spray and seasoning, 25 minutes at 425°F.',
    'Cook once and eat twice. Make extra for lunch tomorrow.'],
    quiz: { q: 'An easy healthy dinner is…', options: ['A sheet-pan meal with protein and vegetables', 'Skipping dinner', 'Fast food'], answer: 0,
      why: 'Sheet-pan meals are quick, easy to clean up, and balanced.' } },
  { title: 'Alcohol', body: [
    'Alcohol has 7 calories per gram, nearly as much as fat, and it lowers your willpower around food.',
    'A couple of beers or glasses of wine can add 300 calories, plus whatever snacking comes with it.',
    'If you drink, alternate with water, choose light beer or wine spritzers, and log it.'],
    quiz: { q: 'Besides its own calories, alcohol can…', options: ['Increase snacking', 'Speed weight loss', 'Replace meals'], answer: 0,
      why: 'Alcohol lowers inhibition, and chips and wings tend to follow.' } },
  { title: 'Plateaus', body: [
    'At some point the scale will stall for a week or two, even when you\'re doing everything right. That\'s normal.',
    'As you lose weight, your body needs fewer calories. This app lowers your budget automatically as you log weigh-ins.',
    'Keep going. Check your portions, add a few more steps, and look at the 4-week trend.'],
    quiz: { q: 'A two-week plateau usually means…', options: ['Give up', 'Stay consistent and check the details', 'Eat much less'], answer: 1,
      why: 'Plateaus are part of the process. Consistency gets you through them.' } },
  { title: 'Non-scale victories', body: [
    'The scale is one measure. It isn\'t the only one.',
    'Notice other wins: pants fitting looser, climbing stairs more easily, better sleep, better blood pressure or blood sugar numbers, more energy.',
    'Write down one non-scale win from this week.'],
    quiz: { q: 'Which is a non-scale victory?', options: ['Clothes fitting better', 'A lower number on the scale', 'Skipping a meal'], answer: 0,
      why: 'These wins keep you motivated when the scale is slow.' } },
  { title: 'Social eating', body: [
    'Family dinners, parties and cookouts are part of life. Enjoy them.',
    'Strategies: eat a green snack before you go, fill your plate once, stand away from the snack table, and focus on the people.',
    '"No thanks, I\'m good" is a complete sentence.'],
    quiz: { q: 'A good party strategy is…', options: ['Arrive starving', 'Have a snack before and fill your plate once', 'Stand by the food'], answer: 1,
      why: 'Arriving hungry makes it much harder to make good choices.' } },
  { title: 'Keeping it off', body: [
    'Losing weight is one skill. Keeping it off is another, and you\'ve been practicing it all along.',
    'People who keep weight off tend to keep weighing in, keep moving, eat breakfast and keep a mostly consistent routine.',
    'You\'ve built real habits. Keep using the ones that work for you, and go easy on yourself when life gets busy.'],
    quiz: { q: 'What helps most with keeping weight off?', options: ['Going back to old habits', 'Keeping the routines that worked', 'Extreme dieting'], answer: 1,
      why: 'The habits that got you here are the same ones that keep you here.' } },
];

const TIPS = [
  'Start dinner with a salad or a bowl of broth-based soup.',
  'Swap chips for baby carrots and hummus.',
  'Put leftovers away before you sit down to eat.',
  'Take a 10-minute walk after your biggest meal.',
  'Use a smaller plate. It really works.',
  'Drink a glass of water before each meal.',
  'Keep a bowl of fruit on the counter.',
  'Try sparkling water with a squeeze of lime.',
  'Add a vegetable to breakfast: spinach in eggs, or tomato on toast.',
  'Weigh in first thing in the morning, same time each day.',
  'Plan tomorrow\'s dinner today.',
  'Chew slowly and put your fork down between bites.',
  'Stand up and stretch every hour.',
  'Order the small size, and you\'ll probably be just as happy.',
];
